### ISSUE TITLE
portlet template customization through portal_view_customization doesn't work properly

### ISSUE THREAD

**Issue by khink** [collective/collective.portlet.content#2]
(http://plone.org/products/collective.portlet.content/issues/2)

When I tried to customize portlet template thru zmi I got an error message as soon as I only had made a copy of the original template.

Exception Type AttributeError
Exception Value REQUEST

Steps to reproduce:
1. Create Content Portlet
2. Go to zmi and start customization process (in portal_view_customization)
3. Check you Content Portlet (you'll get rendering error)

PS. To overcome this I changed a bit of template from

```
        <span>
           <a class="tile"
              tal:attributes="href view/data/more_url"
              tal:content="view/data/header"
              />
        </span>
```

to 
           <span>
               <a class="tile"
                  tal:attributes="href view/content/absolute_url"
                  tal:content="view/content/Title"
                  />
            </span>

It helped but I am not sure about what I've done and that it's a good solution.

**Comment by regebro** [comment]
The good solution is to use z3c.jbot. I suggest closing this as "wontfix".

**Comment by khink** [comment]
Agreed.
