### ISSUE TITLE
portlet permission

### ISSUE THREAD

**Issue by khink** [collective/collective.portlet.content#3]
(http://plone.org/products/collective.portlet.content/issues/3)

Right now the portlet uses cmf.ManagePortal for it's permission. This makes it difficult to allow content editors to use the portlet since we don't like giving out the permission.

Is there any way we could change that to Modify portal content, Portlets: Manage portlets or a new permission so it's easier to give out access for use?

**Comment by afrepues** [comment]
This is fixed in d332a9d8eb.

**Comment by khink** [comment]
Thanks for pointing this out.
